#hogrideaaaaaaaaa
from time import sleep
print("Hogrideaaaaaaaaa")
gameStart = input("Press enter to start:")
print("Teacher: Hey Rhys your homeworks due")
sleep(1)
print("Options:")
sleep(0.5)
print("1. My dog ate it.")
sleep(0.5)
print("2. What homework?")
sleep(0.5)
print("3. I did it I swear I just have to grab it.")
talkOption = input()
if(talkOption == "1"):
    print("Rys: My dog ate it.")
    sleep(0.5)
    print("Teacher: Sure *rolls eyes* I dont even know why I put up with you Rhys go to the principals office.")
elif(talkOption == "2"):
    print("What homework?")
    sleep(0.5)
    print("Teacher: The homework that I assigned yesterday.")
elif(talkOption == "3"):
    print("I did it I swear I just have to grab it.")
    sleep(1)
    print("Teacher: Yeah sure you did go grab it quickly!")
    sleep(1)
    print("You run to your friends class.")
    sleep(1)
    print("You sneak over to your friend.")
    sleep(1)
    print("Hey Owen do you have the homework done that Mrs. Kelly assigned?")
    sleep(1)
    print("Owen: Yeah I have it in my backpack.")
    sleep(1)
    print("You look in Owens backpack the homework is there.")
    sleep(1)
    print("Options:")
    sleep(0.5)
    print("1. Take Owens homework.")
    sleep(0.5)
    print("2. Take a photo of Owens homework.")
    owensHw = input()
    if(owensHw == "1"):
        print("You grab Owens homework and run out of the class.")
        sleep(1)
        print("You are back in your class.")
        sleep(1)
        print("Mrs. Kelly: Do you have your homework?")
    elif(owensHw == "2"):
        print("You grab Owens homework, take a photo of it and run out of the class.")
        sleep(1)
        print("You are back in your class.")
        sleep(1)
        print("Mrs. Kelly: Do you have your homework?")
        sleep(1)
        print("No I dont have it but I do remenber I took a photo of it just in case.")
        sleep(1)
        print("*You show her the photo*")
        sleep(1)
        print("*She doesnt notice it but you forgot to white out Owens name.*")
        sleep(1)
        print("Mrs. Kelly: Well it seems you did do it I guess good job.")
        sleep(1)
        print("Game Complete good job acheivement: Photo")