#hogrideaaaaaaaaa
from time import sleep
print("Hogrideaaaaaaaaa")
gameStart = input("Press enter to start:")
print("Teacher: Hey Rhys your homeworks due")
sleep(1)
print("Options:")
sleep(0.5)
print("1. My dog ate it.")
sleep(0.5)
print("2. What homework?")
sleep(0.5)
print("3. I did it I swear I just have to grab it.")
talkOption = input()
if(talkOption == "1"):
    print("My dog ate it.")
    sleep(1)
    print("Teacher: Sure *rolls eyes* I dont even know why I put up with you Rhys go to the principals office.")
    sleep(1)
    print("You walk to the principals office.")
    sleep(1)
    print("When you get in the principals office he isnt there.")
    sleep(1)
    print("You overhear people talking about how the principal is on his lunch break and wont be back for a while.")
    sleep(1)
    print("Options:")
    sleep(0.5)
    print("1. Go back to class and tell Mrs. McNicol he isnt there.")
    sleep(0.5)
    print("2. Use the principals computer.")
    prinOffice = input()
    if(prinOffice == "1"):
        print("You go back to class and tell Mrs. McNicol that the principal isnt there.")
        sleep(1)
        print("Mrs. McNicol: Oh well I guess Ill have to deal with you later then.")
        sleep(1)
        print("You go back to your seat and wait for the rest of the class to finish and then you go home.")
        sleep(1)
        print("Game Complete! Good job! Achievement: Avoidance")
    elif(prinOffice == "2"):
        print("You sit down at the principas computer.")
        sleep(1)
        print("You turn the computer on.")
        sleep(1)
        comPass = input("Password:")
        while(comPass != "admin123"):
            print("Incorrect password try again.")
            comPass = input("Password:")
            if(comPass == "admin123"):
                print("You log in to the computer.")
                sleep(1)
                print("You find the homework on the computer and print it out.")
                sleep(1)
                print("You take the homework and go back to class.")
                sleep(1)
                print("Mrs. McNicol: Do you have your homework?")
                sleep(1)
                print("Yeah I have it.")
                sleep(1)
                print("*You hand her the homework*")
                sleep(1)
                print("Mrs. McNicol: Well it seems you did do it I guess, good job.")
                sleep(1)
                print("Game Complete! Good job! Acheivement: Hacker")
elif(talkOption == "2"):
    print("What homework?")
    sleep(1)
    print("Teacher: The homework that I assigned yesterday.")
    sleep(1)
    print("Umm I didnt know there was homework yesterday.")
    sleep(1)
    print("Teacher: Rhys I made it very clear yesterday that I assigned homework.")
    sleep(1)
    print("Umm I must have been sick yesterday and missed it.")
    sleep(1)
    print("Teacher: Rhys you have been in school for 3 years now and you still cant remember when I assign homework? Go to the principals office.")
    sleep(1)
    print("You walk to the principals office.")
    sleep(1)
    print("When you get in the principals office the principal asks you why you are there.")
    sleep(1)
    print("You tell him that you forgot about the homework and that Mrs. McNicol sent you to his office.")
    sleep(1)
    print("Principal: You have got to be kidding me Rhys, you forgot about the homework? Do you even pay attention in class? Go back to class already we can have you missing anymore work.")
    sleep(1)
    print("You go back to class and wait for the rest of the class to finish and then you go home.")
    sleep(1)
    print("Game Complete! Good job! Achievement: Forgetfulness")
elif(talkOption == "3"):
    print("I did it I swear I just have to grab it.")
    sleep(1)
    print("Teacher: Yeah sure you did go grab it quickly!")
    sleep(1)
    print("You run to your friends class.")
    sleep(1)
    print("You sneak over to your friend.")
    sleep(1)
    print("Hey Owen do you have the homework done that Mrs. McNicol assigned?")
    sleep(1)
    print("Owen: Yeah I have it in my backpack.")
    sleep(1)
    print("You look in Owens backpack the homework is there.")
    sleep(1)
    print("Options:")
    sleep(0.5)
    print("1. Take Owens homework.")
    sleep(0.5)
    print("2. Take a photo of Owens homework.")
    owensHw = input()
    if(owensHw == "1"):
        print("You grab Owens homework and run out of the class.")
        sleep(1)
        print("You hear him yelling at you as you leave.")
        sleep(1)
        print("You are back in your class.")
        sleep(1)
        print("Mrs. McNicol: Do you have your homework?")
        sleep(1)
        print("Yeah I have it.")
        sleep(1)
        print("*You hand her Owens homework*")
        sleep(1)
        print("*Somehow she doesnt notice at the top there is Owens name*")
        sleep(1)
        print("Mrs. McNicol: Well it seems you did do it I guess, good job.")
        sleep(1)
        print("Game Complete! Good job! Acheivement: Theft")
    elif(owensHw == "2"):
        print("You grab Owens homework, take a photo of it and run out of the class.")
        sleep(1)
        print("You are back in your class.")
        sleep(1)
        print("Mrs. McNicol: Do you have your homework?")
        sleep(1)
        print("No I dont have it but I do remenber I took a photo of it just in case.")
        sleep(1)
        print("*You show her the photo*")
        sleep(1)
        print("*She doesnt notice it but you forgot to white out Owens name.*")
        sleep(1)
        print("Mrs. McNicol: Well it seems you did do it I guess, good job.")
        sleep(1)
        print("Game Complete! Good job! Acheivement: Photo")